#config_version=5

# in modes/credits/config/credits.yaml

#  this gets merged with \mpf\modes\credits\config\credits.yaml   which is
#     C:\Users\David\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\mpf\modes\credits\config
#   it has a priority of 1000010 so it's really high

# following http://docs.missionpinball.org/en/latest/game_logic/credits/index.html?highlight=howto%20credit

# event_player:
    # s_hs_reset_active:
        # #(machine|score1_value):
        # (machine|score1_value):
        # # score1_value:
        # # #(high_score_category)(
            # int: 0
            # action: set   

# variable_player:
    # score_reset:
        # machine|score1_value:
            # int: 0
            # action: set



slide_player:
    credits_added:
        credit_added_slide:
            expire: 2s
    not_enough_credits:
        not_enough_credits_slide:
            expire: 2s
    enabling_free_play:
        enabling_free_play_slide:
            expire: 2s
    enabling_credit_play:
        enabling_credit_play_slide:
            expire: 2s
    max_credits_reached:
        max_credits_reached_slide:
            expire: 2s
    player_added:
        player_added_slide:
            expire: 1s
    TRIscoreSpec:
        TRI_spec_scored_slide:
            expire: 5s
    ZONEscoreSpec:
        ZONE_spec_scored_slide:
            expire: 5s


slides:
    credit_added_slide:
        - type: text
          text: Credit added - thank you
          font_size: 50
          color: purple
        - type: text
          text: (machine|credits_string)
          y: bottom
          anchor_y: bottom
    not_enough_credits_slide:
        - type: text
          text: Insert more coins
          font_size: 50
          color: yellow
        - type: text
          text: (machine|credits_string)
          y: bottom
          anchor_y: bottom
    enabling_free_play_slide:
        - type: text
          text: ENABLING FREE PLAY
    enabling_credit_play_slide:
        - type: text
          text: ENABLING CREDIT PLAY
        - type: text
          text: (machine|credits_string)
    max_credits_reached_slide:
        - type: text
          text: MAX CREDITS REACHED
          font_size: 50
          color: yellow
    player_added_slide:
        - type: text
          text: PLAYER ADDED
          font_size: 50
          color: green
    TRI_spec_scored_slide:
        background_color: 00ff00
        widgets:
            - type: text
              text: TRI Special Pop
              font_size: 50
              color: ff00ff
    ZONE_spec_scored_slide:
        background_color: 0000ff
        widgets:
            - type: text
              text: ZONE Special Pop
              font_size: 50
              color: ff0000
